# Generated by Django 6.0.2 on 2026-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('data_desejada', models.DateField(verbose_name='Data desejada')),
                ('horario_desejado', models.TimeField(verbose_name='Horário desejado')),
                ('objetivo', models.CharField(choices=[('emagrecimento', 'Emagrecimento'), ('hipertrofia', 'Hipertrofia'), ('definicao', 'Definição Muscular'), ('performance', 'Performance/Condicionamento'), ('outro', 'Outro')], max_length=20, verbose_name='Objetivo')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem adicional (opcional)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
