# Generated by Django 6.0.2 on 2026-02-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(help_text='Formato: (11) 99999-9999 ou +5511999999999', max_length=20, verbose_name='Telefone/WhatsApp'),
        ),
    ]
