# Generated by Django 6.0.2 on 2026-02-18 19:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone (ex: fa-book, fa-video)', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='ID da transação no gateway', max_length=200)),
                ('email_compra', models.EmailField(max_length=254)),
                ('nome_compra', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao_curta', models.CharField(help_text='Resumo do produto', max_length=300)),
                ('descricao_completa', models.TextField(help_text='Descrição detalhada em HTML')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagem_capa', models.ImageField(blank=True, upload_to='produtos/capas/')),
                ('video_preview', models.URLField(blank=True, help_text='URL do vídeo de preview (YouTube, Vimeo)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20)),
                ('destaque', models.BooleanField(default=False, help_text='Exibir na página inicial')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('total_vendas', models.PositiveIntegerField(default=0, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-destaque', 'ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ConteudoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vídeo'), ('video_url', 'Vídeo (URL)'), ('texto', 'Texto/HTML'), ('zip', 'Arquivo ZIP'), ('link', 'Link Externo')], max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='produtos/conteudos/')),
                ('url_externa', models.URLField(blank=True, help_text='Para vídeos externos ou links')),
                ('texto_html', models.TextField(blank=True, help_text='Para conteúdo em texto/HTML')),
                ('descricao', models.TextField(blank=True)),
                ('duracao', models.CharField(blank=True, help_text='Ex: 45min, 120 páginas', max_length=50)),
                ('liberado', models.BooleanField(default=True, help_text='Conteúdo disponível para acesso')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Conteúdo Digital',
                'verbose_name_plural': 'Conteúdos Digitais',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='AcessoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, help_text='Deixe vazio para acesso vitalício', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('total_acessos', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Acesso ao Produto',
                'verbose_name_plural': 'Acessos aos Produtos',
                'ordering': ['-liberado_em'],
                'unique_together': {('usuario', 'produto')},
            },
        ),
    ]
