# Generated by Django 6.0.1 on 2026-02-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao_completa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao_curta',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='video_preview',
        ),
        migrations.AddField(
            model_name='produto',
            name='beneficio_1_descricao',
            field=models.TextField(blank=True, default='', verbose_name='Benefício 1 - Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='beneficio_1_titulo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Benefício 1 - Título'),
        ),
        migrations.AddField(
            model_name='produto',
            name='beneficio_2_descricao',
            field=models.TextField(blank=True, default='', verbose_name='Benefício 2 - Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='beneficio_2_titulo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Benefício 2 - Título'),
        ),
        migrations.AddField(
            model_name='produto',
            name='beneficio_3_descricao',
            field=models.TextField(blank=True, default='', verbose_name='Benefício 3 - Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='beneficio_3_titulo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Benefício 3 - Título'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_destaque',
            field=models.ImageField(blank=True, help_text='Imagem para banners/destaques', upload_to='produtos/destaques/', verbose_name='Imagem Destaque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='item_incluso_1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Incluso 1'),
        ),
        migrations.AddField(
            model_name='produto',
            name='item_incluso_2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Incluso 2'),
        ),
        migrations.AddField(
            model_name='produto',
            name='item_incluso_3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Incluso 3'),
        ),
        migrations.AddField(
            model_name='produto',
            name='item_incluso_4',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Incluso 4'),
        ),
        migrations.AddField(
            model_name='produto',
            name='item_incluso_5',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Item Incluso 5'),
        ),
        migrations.AddField(
            model_name='produto',
            name='para_quem_texto',
            field=models.TextField(blank=True, default='', help_text='Descreva o público-alvo', verbose_name='Texto "Para Quem"'),
        ),
        migrations.AddField(
            model_name='produto',
            name='para_quem_titulo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Título "Para Quem"'),
        ),
        migrations.AddField(
            model_name='produto',
            name='subtitulo_hero',
            field=models.CharField(default='', help_text='Ex: Protocolo completo para ganhar massa muscular de forma eficiente', max_length=250, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='texto_cta',
            field=models.CharField(default='Comprar Agora', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='produto',
            name='texto_garantia',
            field=models.TextField(blank=True, default='', help_text='Ex: 7 dias de garantia incondicional', verbose_name='Texto de Garantia'),
        ),
        migrations.AddField(
            model_name='produto',
            name='texto_introducao',
            field=models.TextField(default='', help_text='Parágrafo inicial vendendo o produto', verbose_name='Texto de Introdução'),
        ),
        migrations.AddField(
            model_name='produto',
            name='titulo_hero',
            field=models.CharField(default='', help_text='Ex: Treino para Hipertrofia Muscular', max_length=150, verbose_name='Título Principal'),
        ),
        migrations.AddField(
            model_name='produto',
            name='video_vendas',
            field=models.URLField(blank=True, help_text='URL do vídeo de vendas (YouTube, Vimeo)', verbose_name='Vídeo de Vendas'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Exibir na home e topo do catálogo', verbose_name='Produto em Destaque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Imagem principal do produto', upload_to='produtos/capas/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem no catálogo (menor = primeiro)', verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
    ]
