# Generated by Django 6.0.1 on 2026-02-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_descricao_completa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='subtitulo_hero',
            field=models.CharField(blank=True, default='', help_text='Ex: Protocolo completo para ganhar massa muscular de forma eficiente', max_length=250, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='texto_introducao',
            field=models.TextField(blank=True, default='', help_text='Parágrafo inicial vendendo o produto', verbose_name='Texto de Introdução'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo_hero',
            field=models.CharField(blank=True, default='', help_text='Ex: Treino para Hipertrofia Muscular', max_length=150, verbose_name='Título Principal'),
        ),
    ]
