# Generated by Django 6.0.1 on 2026-02-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_subtitulo_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudodigital',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Para planilhas de treino, infográficos, etc', null=True, upload_to='produtos/imagens/'),
        ),
        migrations.AlterField(
            model_name='conteudodigital',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Para PDF, vídeo, ZIP', null=True, upload_to='produtos/conteudos/'),
        ),
        migrations.AlterField(
            model_name='conteudodigital',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vídeo'), ('video_url', 'Vídeo (URL)'), ('imagem', 'Imagem/Planilha'), ('texto', 'Texto/HTML'), ('zip', 'Arquivo ZIP'), ('link', 'Link Externo')], max_length=20),
        ),
    ]
