# Generated by Django 6.0.2 on 2026-03-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('produtos', '0004_conteudodigital_imagem_alter_conteudodigital_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_cupom',
            field=models.CharField(blank=True, help_text='Código do cupom (preservado mesmo se o cupom for excluído)', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='carrinho.cupom', verbose_name='Cupom'),
        ),
    ]
