# Generated by Django 6.0.2 on 2026-03-02 17:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: BEMVINDO10, NATAL20. Será salvo em maiúsculo.', max_length=50, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor Fixo (R$)')], default='percentual', max_length=10, verbose_name='Tipo de Desconto')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Para percentual: 10 = 10%. Para fixo: 10 = R$ 10,00', max_digits=10, verbose_name='Valor do Desconto')),
                ('valor_minimo_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pedido mínimo para usar o cupom. 0 = sem restrição.', max_digits=10, verbose_name='Valor Mínimo do Pedido')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('validade', models.DateTimeField(blank=True, help_text='Deixe em branco para sem validade.', null=True, verbose_name='Válido até')),
                ('uso_maximo', models.PositiveIntegerField(blank=True, help_text='Quantas vezes pode ser usado no total. Deixe em branco para ilimitado.', null=True, verbose_name='Uso Máximo')),
                ('total_usado', models.PositiveIntegerField(default=0, editable=False, verbose_name='Total de Usos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cupôm',
                'verbose_name_plural': 'Cupõns',
                'ordering': ['-criado_em'],
            },
        ),
    ]
