"""
Django settings for personal project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# =============================================================================
# ENVIRONMENT - Determina se está em DESENVOLVIMENTO ou PRODUÇÃO
# =============================================================================
# Para mudar o ambiente, defina a variável de ambiente DJANGO_ENV:
# - 'production' = Modo Produção (PythonAnywhere, etc)
# - 'development' = Modo Desenvolvimento (padrão)
#
# No PythonAnywhere: adicione no arquivo .env ou defina direto no WSGI
# Localmente: deixe sem definir ou defina DJANGO_ENV=development
# =============================================================================

ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development')
IS_PRODUCTION = ENVIRONMENT == 'production'
IS_DEVELOPMENT = not IS_PRODUCTION

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if IS_PRODUCTION:
    SECRET_KEY = os.environ.get('SECRET_KEY', 'TROQUE-ESTA-SECRET-KEY-POR-UMA-UNICA-E-SEGURA')
else:
    SECRET_KEY = 'TROQUE-ESTA-SECRET-KEY-POR-UMA-UNICA-E-SEGURA'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = IS_DEVELOPMENT

# Hosts permitidos
if IS_PRODUCTION:
    ALLOWED_HOSTS = [
        os.environ.get('ALLOWED_HOST', 'seusite.pythonanywhere.com'),
        'www.' + os.environ.get('ALLOWED_HOST', 'seusite.pythonanywhere.com'),
    ]
else:
    ALLOWED_HOSTS = ['*']  # Permite qualquer host em desenvolvimento


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'agendamento',
    'produtos',
    'dashboard',
    'carrinho',
    'checkout',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'personal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carrinho.context_processors.carrinho',
            ],
        },
    },
]

WSGI_APPLICATION = 'personal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite em todos os ambientes (dev e prod)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    # Comentado para permitir senhas numéricas
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# STATIC_ROOT é necessário para produção (collectstatic)
if IS_PRODUCTION:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
else:
    STATIC_ROOT = None  # Não necessário em desenvolvimento

# Media files (Uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Authentication URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'sales'

# Carrinho de Compras
CART_SESSION_ID = 'carrinho'

# =============================================================================
# MERCADO PAGO - CONFIGURAÇÃO AUTOMÁTICA POR AMBIENTE
# =============================================================================
# As configurações mudam automaticamente baseadas na variável ENVIRONMENT
#
# DESENVOLVIMENTO (DJANGO_ENV != 'production'):
# - Usa credenciais de TESTE
# - Modo sandbox
# - Login obrigatório
# 
# PRODUÇÃO (DJANGO_ENV = 'production'):
# - Usa credenciais de PRODUÇÃO
# - Modo produção
# - Modo convidado ativo
# =============================================================================

if IS_PRODUCTION:
    # ===== PRODUÇÃO =====
    # Suas credenciais de PRODUÇÃO do Mercado Pago
    MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MP_ACCESS_TOKEN_PROD', 'APP-USR-SEU_TOKEN_PRODUCAO')
    MERCADOPAGO_PUBLIC_KEY = os.environ.get('MP_PUBLIC_KEY_PROD', 'APP-USR-SUA_KEY_PRODUCAO')
    MERCADOPAGO_MODE = 'prod'
    MERCADOPAGO_TEST_ONLY = False  # Modo convidado ativo
    MERCADOPAGO_CHECKOUT_POINT = 'init_point'
    MERCADOPAGO_INCLUDE_PAYER = True  # Incluir dados do comprador
else:
    # ===== DESENVOLVIMENTO =====
    # Suas credenciais de TESTE do Mercado Pago
    MERCADOPAGO_ACCESS_TOKEN = os.environ.get('MP_ACCESS_TOKEN_TEST', 'TEST-SEU_TOKEN_TESTE')
    MERCADOPAGO_PUBLIC_KEY = os.environ.get('MP_PUBLIC_KEY_TEST', 'TEST-SUA_KEY_TESTE')
    MERCADOPAGO_MODE = 'test'
    MERCADOPAGO_TEST_ONLY = True  # Login obrigatório
    MERCADOPAGO_CHECKOUT_POINT = 'sandbox_init_point'
    MERCADOPAGO_INCLUDE_PAYER = False

# Configurações comuns
MERCADOPAGO_PAYER_EMAIL_OVERRIDE = ''  # Deixe vazio para usar email do usuário logado
MERCADOPAGO_STATEMENT_DESCRIPTOR = 'PERSONAL TRAINER'  # Aparece na fatura do cartão (max 13 chars alfanum)

# =============================================================================
# CONFIGURAÇÕES DE SEGURANÇA - AUTOMÁTICAS POR AMBIENTE
# =============================================================================
# Em PRODUÇÃO, estas configurações são ativadas automaticamente
# Em DESENVOLVIMENTO, ficam desativadas para facilitar testes locais
# =============================================================================

if IS_PRODUCTION:
    # HTTPS obrigatório (PythonAnywhere suporta HTTPS gratuito)
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Proteção contra clickjacking
    X_FRAME_OPTIONS = 'DENY'
    
    # Prevenir MIME-type sniffing
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Forçar HTTPS por 1 ano (HSTS)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies com SameSite
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # Desenvolvimento: sem restrições de segurança
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# =============================================================================
# LOGGING - Monitoramento de Segurança
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_security': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'verbose',
        },
        'file_mercadopago': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'mercadopago.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['console', 'file_security'],
            'level': 'WARNING',
            'propagate': False,
        },
        'mercadopago': {
            'handlers': ['console', 'file_mercadopago'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file_security'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
