# Generated by Django 6.0.2 on 2026-02-19 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultoriaOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True, verbose_name='Consultoria Ativa')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('treino_arquivo', models.FileField(blank=True, null=True, upload_to='consultoria/treinos/', verbose_name='Arquivo de Treino')),
                ('plano_alimentar_arquivo', models.FileField(blank=True, null=True, upload_to='consultoria/planos_alimentares/', verbose_name='Arquivo de Plano Alimentar')),
                ('medicacao_arquivo', models.FileField(blank=True, null=True, upload_to='consultoria/medicacoes/', verbose_name='Arquivo de Medicação')),
                ('treino_texto', models.TextField(blank=True, verbose_name='Descrição do Treino')),
                ('plano_alimentar_texto', models.TextField(blank=True, verbose_name='Descrição do Plano Alimentar')),
                ('medicacao_texto', models.TextField(blank=True, verbose_name='Descrição da Medicação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Consultoria Online',
                'verbose_name_plural': 'Consultorias Online',
            },
        ),
    ]
