# Generated by Django 6.0.2 on 2026-02-19 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consultoriaonline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Treino A, Peito e Tríceps', max_length=100, verbose_name='Nome do Dia')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Dia de Treino',
                'verbose_name_plural': 'Dias de Treino',
                'ordering': ['treino', 'ordem'],
            },
        ),
        migrations.RemoveField(
            model_name='consultoriaonline',
            name='treino_arquivo',
        ),
        migrations.RemoveField(
            model_name='consultoriaonline',
            name='treino_texto',
        ),
        migrations.CreateModel(
            name='ExercicioTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Exercício')),
                ('series', models.IntegerField(default=3, verbose_name='Séries')),
                ('repeticoes', models.CharField(help_text='Ex: 12, 10-12, até falha', max_length=50, verbose_name='Repetições')),
                ('carga', models.CharField(blank=True, help_text='Ex: 20kg, Peso corporal', max_length=50, verbose_name='Carga')),
                ('descanso', models.CharField(blank=True, help_text='Ex: 60s, 1-2min', max_length=50, verbose_name='Descanso')),
                ('link_video', models.URLField(blank=True, help_text='YouTube, Instagram, etc', verbose_name='Link do Vídeo')),
                ('dica', models.TextField(blank=True, verbose_name='Dica/Observação')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem')),
                ('dia_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='accounts.diatreino', verbose_name='Dia de Treino')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['dia_treino', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Treino')),
                ('tipo', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('emagrecimento', 'Emagrecimento'), ('funcional', 'Funcional'), ('forca', 'Força'), ('resistencia', 'Resistência'), ('outro', 'Outro')], default='hipertrofia', max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Geral')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('duracao_estimada', models.IntegerField(default=60, verbose_name='Duração Estimada (minutos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Treino Atual')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='treinos/', verbose_name='PDF do Treino (opcional)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consultoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='accounts.consultoriaonline', verbose_name='Consultoria')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['-ativo', '-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='diatreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='accounts.treino', verbose_name='Treino'),
        ),
        migrations.CreateModel(
            name='ProgressoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('concluido', models.BooleanField(default=True, verbose_name='Concluído')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='accounts.exerciciotreino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_exercicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Exercício',
                'verbose_name_plural': 'Progressos de Exercícios',
                'unique_together': {('usuario', 'exercicio', 'data')},
            },
        ),
    ]
