# Generated by Django 6.0.2 on 2026-02-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_diatreino_remove_consultoriaonline_treino_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Exercício')),
                ('descricao', models.TextField(blank=True, help_text='Como executar o exercício', verbose_name='Descrição')),
                ('grupo_muscular', models.CharField(blank=True, help_text='Ex: Peito, Costas, Pernas', max_length=100, verbose_name='Grupo Muscular')),
                ('link_video', models.URLField(blank=True, help_text='YouTube, Instagram, etc', verbose_name='Link do Vídeo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='exercicios/', verbose_name='Imagem')),
                ('dica_execucao', models.TextField(blank=True, verbose_name='Dica de Execução')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercício (Banco)',
                'verbose_name_plural': 'Exercícios (Banco)',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='diatreino',
            name='treino',
        ),
        migrations.AlterModelOptions(
            name='exerciciotreino',
            options={'ordering': ['treino', 'ordem'], 'verbose_name': 'Exercício do Treino', 'verbose_name_plural': 'Exercícios do Treino'},
        ),
        migrations.AlterModelOptions(
            name='treino',
            options={'ordering': ['-status', '-criado_em'], 'verbose_name': 'Treino', 'verbose_name_plural': 'Treinos'},
        ),
        migrations.RemoveField(
            model_name='treino',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='duracao_estimada',
        ),
        migrations.RemoveField(
            model_name='treino',
            name='tipo',
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='observacao_especifica',
            field=models.TextField(blank=True, help_text='Observação apenas para este aluno/treino', verbose_name='Observação Específica'),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='treino',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='accounts.treino', verbose_name='Treino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treino',
            name='status',
            field=models.CharField(choices=[('atual', 'Atual'), ('inativo', 'Inativo')], default='atual', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='exercicio',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='accounts.exercicio', verbose_name='Exercício'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='exerciciotreino',
            unique_together={('treino', 'exercicio', 'ordem')},
        ),
        migrations.DeleteModel(
            name='ProgressoExercicio',
        ),
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='dia_treino',
        ),
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='dica',
        ),
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='link_video',
        ),
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='nome',
        ),
        migrations.DeleteModel(
            name='DiaTreino',
        ),
    ]
