# Generated by Django 6.0.2 on 2026-02-19 16:52

import django.db.models.deletion
from django.db import migrations, models


def criar_dia_padrao(apps, schema_editor):
    Treino = apps.get_model('accounts', 'Treino')
    DiaTreino = apps.get_model('accounts', 'DiaTreino')
    ExercicioTreino = apps.get_model('accounts', 'ExercicioTreino')

    for treino in Treino.objects.all():
        dia, _ = DiaTreino.objects.get_or_create(
            treino=treino,
            nome='Treino A',
            defaults={'ordem': 1, 'descricao': ''},
        )
        ExercicioTreino.objects.filter(treino=treino, dia_treino__isnull=True).update(dia_treino=dia)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exercicio_remove_diatreino_treino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciciotreino',
            options={'ordering': ['dia_treino', 'ordem'], 'verbose_name': 'Exercício do Treino', 'verbose_name_plural': 'Exercícios do Treino'},
        ),
        migrations.CreateModel(
            name='DiaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Treino A, Superior, Pernas', max_length=100, verbose_name='Nome do Dia')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='accounts.treino', verbose_name='Treino')),
            ],
            options={
                'verbose_name': 'Dia de Treino',
                'verbose_name_plural': 'Dias de Treino',
                'ordering': ['treino', 'ordem'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='exerciciotreino',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exerciciotreino',
            name='dia_treino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='accounts.diatreino', verbose_name='Dia de Treino'),
        ),
        migrations.RunPython(criar_dia_padrao, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exerciciotreino',
            name='dia_treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='accounts.diatreino', verbose_name='Dia de Treino'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciciotreino',
            unique_together={('dia_treino', 'exercicio', 'ordem')},
        ),
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='treino',
        ),
    ]
