# Generated by Django 6.0.1 on 2026-05-02 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_exerciciotreino_options_diatreino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('abandonada', 'Abandonada')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('dia_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='accounts.diatreino', verbose_name='Dia de Treino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_treino', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Treino',
                'verbose_name_plural': 'Sessões de Treino',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='SerieRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.IntegerField(verbose_name='Número da Série')),
                ('carga_usada', models.CharField(blank=True, max_length=50, verbose_name='Carga Usada')),
                ('repeticoes_realizadas', models.CharField(blank=True, max_length=50, verbose_name='Repetições Realizadas')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('tempo_descanso_segundos', models.IntegerField(blank=True, null=True, verbose_name='Descanso Real (s)')),
                ('exercicio_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_realizadas', to='accounts.exerciciotreino', verbose_name='Exercício do Treino')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='accounts.sessaotreino', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Série Realizada',
                'verbose_name_plural': 'Séries Realizadas',
                'ordering': ['exercicio_treino__ordem', 'numero_serie'],
                'unique_together': {('sessao', 'exercicio_treino', 'numero_serie')},
            },
        ),
    ]
